services:
    - postgresql
language: rust
rust:
  - stable
install:
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
    - cargo test
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
